-- $BEGIN
CREATE TABLE mamba_fact_audit_tool_art_patients
(
    id                                      INT AUTO_INCREMENT,
    client_id                               INT NOT NULL,
    cd4                                     INT NULL,
    nationality                             VARCHAR(100) NULL,
    marital_status                          VARCHAR(80) NULL,
    birthdate                               DATE NULL,
    dead                                    BIT NOT NULL,
    gender                                  VARCHAR(100) NULL,
    last_visit_date                         DATE NULL,
    return_visit_date                       DATE NULL,
    days_left_to_be_lost                    INT NULL,
    transfer_out_date                       DATE NULL,
    current_arv_regimen                     VARCHAR(100) NULL,
    arv_regimen_start_date                  DATE NULL,
    adherence_assessment_code               VARCHAR(80) NULL,
    arv_regimen_days_dispensed              INT NULL,
    hiv_viral_load                          INT NULL,
    hiv_viral_load_date                     DATE NULL,
    new_sample_collection_date              DATE NULL,
    advanced_disease_status                 VARCHAR(250) NULL,
    family_planning_status                  VARCHAR(250) NULL,
    nutrition_assessment                    VARCHAR(80) NULL,
    nutrition_support_and_infant_feeding    VARCHAR(80) NULL,
    hepatitis_b_test_qualitative            VARCHAR(250) NULL,
    syphilis_test_result_for_partner        VARCHAR(250) NULL,
    cervical_cancer_screening               VARCHAR(250) NULL,
    tuberculosis_status                     VARCHAR(250) NULL,
    tpt_status                              VARCHAR(250) NULL,
    cd4_count                               INT NULL,
    crag_test_results                       VARCHAR(250) NULL,
    who_hiv_clinical_stage                  VARCHAR(250) NULL,
    differentiated_service_delivery         VARCHAR(250) NULL,
    baseline_cd4                            INT NULL,
    baseline_regimen_start_date             DATE NULL,
    special_category                        VARCHAR(250) NULL,
    regimen_line                            VARCHAR(250) NULL,
    health_education_setting                VARCHAR(250) NULL,
    pss_issues_identified                   VARCHAR(250) NULL,
    art_preparation                         VARCHAR(250) NULL,
    depression_status                       VARCHAR(250) NULL,
    gender_based_violence                   VARCHAR(250) NULL,
    health_education_disclosure             VARCHAR(250) NULL,
    ovc_screening                           VARCHAR(250) NULL,
    ovc_assessment                          VARCHAR(250) NULL,
    prevention_components                   VARCHAR(250) NULL,
    linkages_and_refferals                  VARCHAR(250) NULL,
    iac_sessions                            INT NULL,
    hivdr_results                           VARCHAR(250) NULL,
    date_hivdr_results_received_at_facility DATE NULL,
    vl_after_iac                            INT NULL,
    decision_outcome                        VARCHAR(250) NULL,

    PRIMARY KEY (id)
) CHARSET = UTF8MB4;

-- $END

