-- $BEGIN
CREATE TABLE mamba_fact_eid_patients
(
    id        INT AUTO_INCREMENT,
    client_id INT NOT NULL,
    EDD VARCHAR(80) DEFAULT NULL ,
    EID_NO VARCHAR(80) DEFAULT NULL ,
    EID_DOB VARCHAR(80) DEFAULT NULL ,
    EID_AGE VARCHAR(80) DEFAULT NULL ,
    EID_WEIGHT VARCHAR(80) DEFAULT NULL ,
    EID_NEXT_APPT varchar(80) DEFAULT NULL,
    EID_FEEDING varchar(80) DEFAULT NULL,
    CTX_START varchar(80) DEFAULT NULL,
    CTX_AGE varchar(80) DEFAULT NULL,
    1ST_PCR_DATE varchar(80) DEFAULT NULL,
    1ST_PCR_AGE varchar(80) DEFAULT NULL,
    1ST_PCR_RESULT varchar(80) DEFAULT NULL,
    1ST_PCR_RECEIVED varchar(80) DEFAULT NULL,
    2ND_PCR_DATE varchar(80) DEFAULT NULL,
    2ND_PCR_AGE varchar(80) DEFAULT NULL,
    2ND_PCR_RESULT varchar(80) DEFAULT NULL,
    2ND_PCR_RECEIVED varchar(80) DEFAULT NULL,
    REPEAT_PCR_DATE varchar(80) DEFAULT NULL,
    REPEAT_PCR_AGE varchar(80) DEFAULT NULL,
    REPEAT_PCR_RESULT varchar(80) DEFAULT NULL,
    REPEAT_PCR_RECEIVED varchar(80) DEFAULT NULL,
    RAPID_PCR_DATE varchar(80) DEFAULT NULL,
    RAPID_PCR_AGE varchar(80) DEFAULT NULL,
    RAPID_PCR_RESULT varchar(80) DEFAULT NULL,
    FINAL_OUTCOME varchar(80) DEFAULT NULL,
    LINKAGE_NO varchar(80) DEFAULT NULL,
    NVP_AT_BIRTH varchar(80) DEFAULT NULL,

    PRIMARY KEY (id)
) CHARSET = UTF8MB4;

-- $END

