-- $BEGIN
INSERT INTO mamba_fact_encounter_hts_card (encounter_id,
                                           client_id,
                                           family_member_accompanying_patient, other_specified_family_member,
                                           delivery_model, counselling_approach, hct_entry_point,
                                           community_testing_point, other_community_testing, anc_visit_number,
                                           other_care_entry_point, reason_for_testing, reason_for_testing_other_specify,
                                           special_category, other_special_category, hiv_first_time_tester,
                                           previous_hiv_tests_date, months_since_first_hiv_aids_symptoms,
                                           previous_hiv_test_results, referring_health_facility,
                                           no_of_times_tested_in_last_12_months, no_of_partners_in_the_last_12_months,
                                           partner_tested_for_hiv, partner_hiv_test_result,
                                           pre_test_counseling_done, counselling_session_type,
                                           current_hiv_test_result, hiv_syphilis_duo,
                                           consented_for_blood_drawn_for_testing, hiv_recency_result,
                                           hiv_recency_viral_load_results, hiv_recency_viral_load_qualitative,
                                           hiv_recency_sample_id, hts_fingerprint_captured,
                                           results_received_as_individual, results_received_as_a_couple,
                                           couple_results, tb_suspect, presumptive_tb_case_referred,
                                           prevention_services_received, other_prevention_services,
                                           has_client_been_linked_to_care, name_of_location_transferred_to)
SELECT encounter_id,
       client_id,
       family_member_accompanying_patient,
       other_specified_family_member,
       delivery_model,
       counselling_approach,
       hct_entry_point,
       community_testing_point,
       other_community_testing,
       anc_visit_number,
       other_care_entry_point,
       reason_for_testing,
       reason_for_testing_other_specify,
       special_category,
       other_special_category,
       hiv_first_time_tester,
       previous_hiv_tests_date,
       months_since_first_hiv_aids_symptoms,
       previous_hiv_test_results,
       referring_health_facility,
       no_of_times_tested_in_last_12_months,
       no_of_partners_in_the_last_12_months,
       partner_tested_for_hiv,
       partner_hiv_test_result,
       pre_test_counseling_done,
       counselling_session_type,
       current_hiv_test_result,
       hiv_syphilis_duo,
       consented_for_blood_drawn_for_testing,
       hiv_recency_result,
       hiv_recency_viral_load_results,
       hiv_recency_viral_load_qualitative,
       hiv_recency_sample_id,
       hts_fingerprint_captured,
       results_received_as_individual,
       results_received_as_a_couple,
       couple_results,tb_suspect,
       presumptive_tb_case_referred,
       prevention_services_received,
       other_prevention_services,
       has_client_been_linked_to_care,
       name_of_location_transferred_to

FROM mamba_flat_encounter_hts_card
where encounter_datetime >= DATE_SUB(CURRENT_DATE(), INTERVAL 5 YEAR);
-- $END