-- $BEGIN
CREATE TABLE mamba_fact_encounter_hiv_art_card
(
    id                                    INT AUTO_INCREMENT,
    encounter_id                          INT          NULL,
    client_id                             INT          NULL,
    encounter_date                        DATE         NULL,

    method_of_family_planning             VARCHAR(80) NULL,
    cd4                                   VARCHAR(80) NULL,
    hiv_viral_load                        VARCHAR(80) NULL,
    historical_drug_start_date            VARCHAR(80) NULL,
    historical_drug_stop_date             VARCHAR(80) NULL,
    medication_orders                     VARCHAR(80) NULL,
    viral_load_qualitative                VARCHAR(80) NULL,
    hepatitis_b_test___qualitative        VARCHAR(80) NULL,
    duration_units                        VARCHAR(80) NULL,
    return_visit_date                     VARCHAR(80) NULL,
    cd4_count                             VARCHAR(80) NULL,
    estimated_date_of_confinement         VARCHAR(80) NULL,
    pmtct                                 VARCHAR(80) NULL,
    pregnant                              VARCHAR(80) NULL,
    scheduled_patient_visist              VARCHAR(80) NULL,
    who_hiv_clinical_stage                VARCHAR(80) NULL,
    name_of_location_transferred_to       VARCHAR(80) NULL,
    tuberculosis_status                   VARCHAR(80) NULL,
    tuberculosis_treatment_start_date     VARCHAR(80) NULL,
    adherence_assessment_code             VARCHAR(80) NULL,
    reason_for_missing_arv_administration VARCHAR(80) NULL,
    medication_or_other_side_effects      VARCHAR(80) NULL,
    family_planning_status                VARCHAR(80) NULL,
    symptom_diagnosis                     VARCHAR(80) NULL,
    transfered_out_to_another_facility    VARCHAR(80) NULL,
    tuberculosis_treatment_stop_date      VARCHAR(80) NULL,
    current_arv_regimen                   VARCHAR(80) NULL,
    art_duration                          VARCHAR(80) NULL,
    current_art_duration                  VARCHAR(80) NULL,
    mid_upper_arm_circumference_code      VARCHAR(80) NULL,
    district_tuberculosis_number          VARCHAR(80) NULL,
    other_medications_dispensed           VARCHAR(255) NULL,
    arv_regimen_days_dispensed            VARCHAR(80) NULL,
    ar_regimen_dose                       VARCHAR(80) NULL,
    nutrition_support_and_infant_feeding  VARCHAR(80) NULL,
    other_side_effects                    VARCHAR(80) NULL,
    other_reason_for_missing_arv          VARCHAR(80) NULL,
    current_regimen_other                 VARCHAR(80) NULL,
    transfer_out_date                     VARCHAR(80) NULL,
    cotrim_given                          VARCHAR(80) NULL,
    syphilis_test_result_for_partner      VARCHAR(80) NULL,
    eid_visit_1_z_score                   VARCHAR(80) NULL,
    medication_duration                   VARCHAR(80) NULL,
    medication_prescribed_per_dose        VARCHAR(80) NULL,
    tuberculosis_polymerase               VARCHAR(80) NULL,
    specimen_sources                      VARCHAR(80) NULL,
    estimated_gestational_age             VARCHAR(80) NULL,
    hiv_viral_load_date                   VARCHAR(80) NULL,
    other_reason_for_appointment          VARCHAR(80) NULL,
    nutrition_assesment                   VARCHAR(80) NULL,
    differentiated_service_delivery       VARCHAR(80) NULL,
    stable_in_dsdm                        VARCHAR(80) NULL,
    tpt_start_date                        VARCHAR(80) NULL,
    tpt_completion_date                   VARCHAR(80) NULL,
    advanced_disease_status               VARCHAR(80) NULL,
    tpt_status                            VARCHAR(80) NULL,
    rpr_test_results                      VARCHAR(80) NULL,
    crag_test_results                     VARCHAR(80) NULL,
    tb_lam_results                        VARCHAR(80) NULL,
    cervical_cancer_screening             VARCHAR(80) NULL,
    intention_to_conceive                 VARCHAR(80) NULL,
    tb_microscopy_results                 VARCHAR(80) NULL,
    quantity_unit                         VARCHAR(80) NULL,
    tpt_side_effects                      VARCHAR(80) NULL,
    lab_number                            TEXT NULL,
    test                                  VARCHAR(80) NULL,
    test_result                           VARCHAR(80) NULL,
    refill_point_code                     VARCHAR(80) NULL,
    next_return_date_at_facility          VARCHAR(80) NULL,
    indication_for_viral_load_testing     VARCHAR(80) NULL,

    PRIMARY KEY (id)
)
    CHARSET = UTF8MB4;

-- $END

