-- $BEGIN
INSERT INTO mamba_fact_encounter_non_suppressed_card (encounter_id,
                                                      client_id,
                                                      encounter_date,
                                                      vl_qualitative, register_serial_number, cd4_count,
                                                      tuberculosis_status, current_arv_regimen, breast_feeding,
                                                      eligible_for_art_pregnant, clinical_impression_comment,
                                                      hiv_vl_date, date_vl_results_received_at_facility, session_date,
                                                      adherence_assessment_score, date_vl_results_given_to_client,
                                                      serum_crag_screening_result, serum_crag_screening, restarted_iac,
                                                      hivdr_sample_collected, tb_lam_results, date_cd4_sample_collected,
                                                      date_of_vl_sample_collection, on_fluconazole_treatment,
                                                      tb_lam_test_done, date_hivr_results_recieved_at_facility,
                                                      hivdr_results)
SELECT encounter_id,
       client_id,
       encounter_datetime,
       vl_qualitative,
       register_serial_number,
       cd4_count,
       tuberculosis_status,
       current_arv_regimen,
       breast_feeding,
       eligible_for_art_pregnant,
       clinical_impression_comment,
       hiv_vl_date,
       date_vl_results_received_at_facility,
       session_date,
       adherence_assessment_score,
       date_vl_results_given_to_client,
       serum_crag_screening_result,
       serum_crag_screening,
       restarted_iac,
       hivdr_sample_collected,
       tb_lam_results,
       date_cd4_sample_collected,
       date_of_vl_sample_collection,
       on_fluconazole_treatment,
       tb_lam_test_done,
       date_hivr_results_recieved_at_facility,
       hivdr_results

FROM mamba_flat_encounter_non_suppressed;
-- $END